version: "3"

#/etc/hosts
x-hosts: &hosts
  - store.local.55haitao.com:${NGINX_IP}
  - maxrebates.local.55haitao.com:${NGINX_IP}
  - affiliate-source.local.55haitao.com:${NGINX_IP}
  - gocashback.local.55haitao.com:${NGINX_IP}
  - esb-user.local.55haitao.com:${NGINX_IP}
  - esb-base.local.55haitao.com:${NGINX_IP}
  - esb-utils.local.55haitao.com:${NGINX_IP}
  - hub.local.55haitao.com:${NGINX_IP}
  - esb-api.local.55haitao.com:${NGINX_IP}
  - esb-medium.local.55haitao.com:${NGINX_IP}

services:
  nginx:
    image: mcskyding/nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/etc/nginx/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      # - default
      # 可以把-default 改成下列配置，以固定容器IP
      default:
        ipv4_address: ${NGINX_IP}

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ./services/nginx/ssl/:/etc/letsencrypt/:rw
    networks:
      default:
        ipv4_address: ${CERTBOT_IP}

  php56:
    image: ${REPOSITORY}/php:${PHP56_VERSION}
    container_name: php56
    expose:
      - 9501
    extra_hosts: *hosts
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP56_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php72:
    image: ${REPOSITORY}/php:${PHP72_VERSION}
    container_name: php72
    expose:
      - 9501
    extra_hosts:
      - "esb-base.local.55haitao.com:10.0.0.10"
      - "affiliate-source.local.55haitao.com:10.0.0.10"
      - "esb-utils.local.55haitao.com:10.0.0.10"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP7_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP7_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP7_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
      
  php74:
    image: ${REPOSITORY}/php:${PHP74_VERSION}
    container_name: php74
    expose:
      - 9501
    extra_hosts: *hosts
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP7_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP7_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP7_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php81:
      image: ${REPOSITORY}/php:${PHP81_VERSION}
      container_name: php81
      expose:
        - 9501
      volumes:
        - ${SOURCE_DIR}:/www/:rw
        - ${PHP81_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
        - ${PHP81_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
        - ${PHP81_LOG_DIR}:/var/log/php
        - ${DATA_DIR}/composer:/tmp/composer
        - ${PHP81_LOG_DIR}/cron:/var/log/cron
      extra_hosts: *hosts
      restart: always
      cap_add:
        - SYS_PTRACE
      networks:
        - default

  php82:
    image: ${REPOSITORY}/php:${PHP82_VERSION}
    container_name: php82
    expose:
      - 9501
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP82_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP82_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP82_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ${PHP82_LOG_DIR}/cron:/var/log/cron
    extra_hosts: *hosts
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php83:
    image: ${REPOSITORY}/php:${PHP83_VERSION}
    container_name: php83
    expose:
      - 9501
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP83_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP83_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP83_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ${PHP83_LOG_DIR}/cron:/var/log/cron
    extra_hosts: *hosts
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"
      TZ: "$TZ"

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - default
      
  mysql5:
    image: mysql:${MYSQL5_VERSION}
    container_name: mysql5
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
      - ${MYSQL5_LOG_DIR}:/var/log/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "${MYSQL5_ROOT_HOST}"
      TZ: "$TZ"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      # 解除下面的注释可以设置网段，用于nginx等容器固定容器IP
      config:
        - subnet: ${SUBNET_IP}
