version: "3"

#/etc/hosts
x-hosts: &hosts
  - store.local.55haitao.com:${NGINX_IP}
  - maxrebates.local.55haitao.com:${NGINX_IP}
  - affiliate-source.local.55haitao.com:${NGINX_IP}
  - gocashback.local.55haitao.com:${NGINX_IP}
  - esb-user.local.55haitao.com:${NGINX_IP}
  - esb-base.local.55haitao.com:${NGINX_IP}
  - esb-utils.local.55haitao.com:${NGINX_IP}
  - hub.local.55haitao.com:${NGINX_IP}
  - esb-api.local.55haitao.com:${NGINX_IP}
  - esb-medium.local.55haitao.com:${NGINX_IP}

services:
  nginx:
    image: mcskyding/nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/etc/nginx/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      # - default
      # 可以把-default 改成下列配置，以固定容器IP
      default:
        ipv4_address: ${NGINX_IP}

  php83:
    image: ${REPOSITORY}/php:${PHP83_VERSION}
    container_name: php83
    expose:
      - 9501
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP83_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP83_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP83_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    extra_hosts: *hosts
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      default:
        ipv4_address: ${REDIS_IP}

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      # 解除下面的注释可以设置网段，用于nginx等容器固定容器IP
      config:
        - subnet: ${SUBNET_IP}
