version: '3'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/skyting/nginx:1.19.1
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/case:/opt/case:rw
      - /opt/app/nginx/conf/nginx.conf:/opt/app/nginx/conf/nginx.conf
      - /opt/app/nginx/conf/conf.d/:/opt/app/nginx/conf/conf.d
      - /opt/app/nginx/conf/ssl/:/opt/app/nginx/conf/ssl/
      - /opt/logs/nginx/:/opt/logs/nginx/
    networks:
      - default
    links:
      - php
#
  php:
    image: registry.cn-hangzhou.aliyuncs.com/skyting/php:7.4.8
    container_name: php
    restart: always
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - /opt/app/php/etc/php.ini:/opt/app/php/etc/php.ini
      - /opt/logs/php/:/opt/logs/php/
      - /opt/case:/opt/case:rw
    networks:
      - default

networks:
  default:
    external:
      name: sky