version: '3'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/skyting/nginx:1.19.1
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Users/dingmingchun/SourceCode:/opt/case:rw
      - /Users/dingmingchun/Develop/nginx/conf/nginx.conf:/opt/app/nginx/conf/nginx.conf
      - /Users/dingmingchun/Develop/nginx/conf/conf.d/:/opt/app/nginx/conf/conf.d
      - /Users/dingmingchun/Develop/nginx/conf/ssl/:/opt/app/nginx/conf/ssl/
      - /Users/dingmingchun/Develop/logs/:/opt/logs/
    networks:
      - default
    links:
      - php

  php:
    image: registry.cn-hangzhou.aliyuncs.com/skyting/php:7.4.8
    container_name: php
    restart: always
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - /Users/dingmingchun/Develop/php/etc/php.ini:/opt/app/php/etc/php.ini
      - /Users/dingmingchun/Develop/php/etc/cron.ini:/opt/app/php/etc/cron.ini
      - /Users/dingmingchun/SourceCode:/opt/case:rw
      - /Users/dingmingchun/Develop/logs:/opt/logs/
    extra_hosts:
      - "test.bumblebee.2345.cn:172.17.18.169"
      - "xhgui.web.2345.cn:172.17.12.70"
    networks:
      - default
    links:
      - redis


#  mysql:
#   image: repo-docker.2345.com:8088/starnews.2345.com/mysql:5.7.23
#   restart: always
#   container_name: mysql
#   ports:
#   - "3308:3306"
#   volumes:
#   - /opt/app/starnews/mysql/tmp/:/opt/app/mysql57/tmp/
#   - /opt/app/starnews/mysql/var/:/opt/app/mysql57/var/
#   - /opt/app/starnews/mysql/data/:/opt/app/mysql57/data/
#   - /opt/app/starnews/mysql/logs/:/opt/app/mysql57/logs/
#   environment:
#     MYSQL_ROOT_PASSWORD: 123456
#   networks:
#     - default:

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/skyting/redis:6.0.6
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - /Users/dingmingchun/Develop/redis/logs/:/opt/app/redis/logs/
      - /Users/dingmingchun/Develop/redis/db/:/opt/app/redis/db/
    networks:
      - default
networks:
  default:
    external:
      name: sky