version: '3'
services:
#  nginx:
#    image: repo-docker.2345.com:8088/starnews.2345.com/nginx:1.12.2
#    container_name: starnews_nginx
#    restart: always
#    ports:
#    - "8083:80"
#    volumes:
#    - /opt/case/:/opt/case
#    - /opt/app/starnews/nginx/logs:/opt/app/nginx/logs
#    # - /opt/app/starnews/nginx/conf/nginx.conf:/opt/app/nginx/conf/nginx.conf
#    # - /opt/app/starnews/nginx/conf/sites:/opt/app/nginx/conf/sites
#    networks:
#      mywebnet:
#        ipv4_address: 10.11.0.2
#    links:
#    - php
#
#  php:
#    image: repo-docker.2345.com:8088/starnews.2345.com/php:7.2.11
#    container_name: starnews_php
#    restart: always
#    volumes:
#    - /opt/case:/opt/case
#    # - /opt/app/starnews/php/etc/php-fpm.conf:/opt/app/php7/etc/php-fpm.conf
#    # - /opt/app/starnews/php/etc/php.ini:/opt/app/php7/etc/php.ini
#    # - /opt/app/starnews/php/etc/cron.ini:/opt/app/php7/etc/cron.ini
#    - /opt/app/starnews/php/logs/:/opt/logs/php7/
#    extra_hosts:
#    - "passport.2345.com:172.17.18.185"
#    - "login.2345.com:172.17.18.185"
#    - "houtai.2345.com:172.17.12.70"
#    - "test.dsp.union2.50bang.org:172.16.0.110"
#    - "test.bumblebee.2345.cn:172.17.18.169"
#    - "xq.2345.com:172.17.12.70"
#    - "imgwx1.2345.com:172.17.12.70"
#    - "newsapp.2345.com:172.17.12.47"
#    - "xhgui.web.2345.cn:172.17.12.70"
#    - "www.adintercept.com:172.17.18.116"
#    - "starnews.2345.com:172.17.12.70"
#    networks:
#      mywebnet:
#        ipv4_address: 10.11.0.3
#
#  mysql:
#   image: repo-docker.2345.com:8088/starnews.2345.com/mysql:5.7.23
#   restart: always
#   container_name: starnews_mysql
#   ports:
#   - "3308:3306"
#   volumes:
#   - /opt/app/starnews/mysql/tmp/:/opt/app/mysql57/tmp/
#   - /opt/app/starnews/mysql/var/:/opt/app/mysql57/var/
#   - /opt/app/starnews/mysql/data/:/opt/app/mysql57/data/
#   - /opt/app/starnews/mysql/logs/:/opt/app/mysql57/logs/
#   environment:
#     MYSQL_ROOT_PASSWORD: 123456
#   networks:
#     mywebnet:
#       ipv4_address: 10.11.0.4

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/skyting/redis:5.0.8
    restart: always
    container_name: redis
    ports:
    - "6379:6379"
    volumes:
#     - /opt/app/starnews/redis/logs/:/opt/app/redis/logs/
     - D:\Develop\redis\logs\:/opt/app/redis/logs/
#     - /opt/app/starnews/redis/db/:/opt/app/redis/db/
     - D:\Develop\redis\db\:/opt/app/redis/db/
    networks:
      - default
networks:
  default:
    ipam:
      config:
      - subnet: 172.20.0.1/24